### ISSUE TITLE
Use canonical protoc-gen-go instead of forking

### ISSUE THREAD

**Issue by technicallyty** [cosmos/cosmos-proto#13]
### Currently we have a LOT of code copied from protoc-gen-go. 

Our initial approach was to attempt to create a protoc-gen-go-lite and only generate what was needed, but as we found a need for descriptors and protoc lang features, more code was needed from protoc-gen-go. 

### I think we should reconsider this approach and use plugins alongside protoc-gen-go like VT's plugin, and frojdi's fast plugin. 

The issue that was brought up from using isolated plugins was that we would end up with multiple generated files per proto file. Solutions to this problem:

- All generated files in modules could go under their own folder. For example:
`x/upgrade/generated/*.pb.go`
- Create a tool that combines multiple go src files using go/ast

**Comment by aaronc** [comment]
Seems like the AST combination approach will allow us to reuse code but also override `protoreflect.Message` from protoc-gen-go, right? If so, the AST approach makes sense

**Comment by technicallyty** [comment]
> Seems like the AST combination approach will allow us to reuse code but also override `protoreflect.Message` from protoc-gen-go, right? If so, the AST approach makes sense

We don't actually have to get in the guts of protoc-gen-go to do that - we can just make another isolated plugin that generates the interface methods. example: https://github.com/cosmos/cosmos-proto/blob/ty/example-pm-go/proto/foo.pm.go

**Comment by aaronc** [comment]
> > Seems like the AST combination approach will allow us to reuse code but also override `protoreflect.Message` from protoc-gen-go, right? If so, the AST approach makes sense
> 
> We don't actually have to get in the guts of protoc-gen-go to do that - we can just make another isolated plugin that generates the interface methods. example: https://github.com/cosmos/cosmos-proto/blob/ty/example-pm-go/proto/foo.pm.go

But that doesn't work. We need to override the `ProtoReflect()` method itself and return a separate type as per https://github.com/cosmos/cosmos-proto/issues/7#issuecomment-882672338

**Comment by technicallyty** [comment]
> > > Seems like the AST combination approach will allow us to reuse code but also override `protoreflect.Message` from protoc-gen-go, right? If so, the AST approach makes sense
> > 
> > 
> > We don't actually have to get in the guts of protoc-gen-go to do that - we can just make another isolated plugin that generates the interface methods. example: https://github.com/cosmos/cosmos-proto/blob/ty/example-pm-go/proto/foo.pm.go
> 
> But that doesn't work. We need to override the `ProtoReflect()` method itself and return a separate type as per [#7 (comment)](https://github.com/cosmos/cosmos-proto/issues/7#issuecomment-882672338)

Ahh - keep forgetting about that method, looks like AST is the only way out then

**Comment by technicallyty** [comment]
i think it might be best to just delete the `ProtoReflect()` method from the AST and leave that up to our protomessage iface plugin, rather than just patching it to make it return X. That way we can control it even more if we need to do any side effects in that function. 

So a shell script can simply find all .pb.go files and remove the `ProtoReflect` method and rewrite the file to disk.

but also i think this may be an oversight by the golang/protobuf implementation. What's the point of exposing the message interface if calling protoreflect just overwrites it? am i missing something here?

**Comment by technicallyty** [comment]
made a tool for the AST patching here - https://github.com/technicallyty/nana

it supports 
- removing a function from an AST and rewriting the src file to disk
- merging a list of dst files into a src file

next steps would be to merge this into a make file script, although the docker stuff is still not working on my machine so kinda blocked there

**Comment by technicallyty** [comment]
fixed https://github.com/cosmos/cosmos-proto/commit/99bf1d072bc16481e07dea4a0424279b20e2e921
