### ISSUE TITLE
Consider "slow" protobuf as a build tag

### ISSUE THREAD

**Issue by fdymylja** [cosmos/cosmos-proto#14]
Whilst iterating over the official goproto repo, many developers asked for reasons for which code generation fast paths (specifically related to marshalling/unmarshalling) implementation were never done. One of the answers given by the owners was that the big code size was a [problem for some environments](https://github.com/golang/protobuf/issues/1225#issuecomment-714816062).

Might this something we need to consider in the scope of the cosmos ecosystem?

A solution could be generating a build tag for slow paths, ex:

types.slow.pb.go
```golang
// +build slow

... reflection code...

```

types.pb.go

```golang
// +build !slow
.. fast path code ...
```

**Comment by aaronc** [comment]
Sounds like a great idea!
