### ISSUE TITLE
Reconcile protoreflect.Message.ProtoMethods codegen

### ISSUE THREAD

**Issue by fdymylja** [cosmos/cosmos-proto#18]
Currently, fastreflection implements protomethods as `nil`, which means that in order to marshal a protobuf message, it's going to get the fields one by one using `protoreflect.Message.Range`. We should reconcile this with the fastmarshal implementation.

**Comment by technicallyty** [comment]
should the methods _only_ work on messages of the same type? 

i.e. if someone calls `ProtoMethods` on a proto message type `Foo`, should those methods _only_ work on type `Foo` messages?

or should `ProtoMethods` return methods that work on _anything_ ?

**Comment by aaronc** [comment]
Only on that type
