### ISSUE TITLE
Fast-path protoreflect.Message methods

### ISSUE THREAD

**Issue by aaronc** [cosmos/cosmos-proto#3]
Needed for custom types and `Any`s, will also speed up other codes.

Types to implement:

ProtoReflect.Messsage:

- [x] Descriptor
- [x] Type
- [x] New
- [x] Interface
- [x] Range
- [x] Has
- [x] Clear
- [x] Get:
    - [x] Scalar types
    - [x] Oneof types
    - [x] Message types
    - [x] List types
    - [x] Map types
    - [ ] Extension Types
- [x] Set
- [x] Mutable
- [x] NewField
- [x] WhichOneof
- [x] GetUnknown
- [x] SetUnknown
- [x] IsValid 

Protoreflect.List:
- [x] Len
- [x] Get
- [x] Set
- [x] Append
- [x] AppendMutable
- [x] Truncate
- [x] NewElement
- [x] IsValid

Protoreflect.Map:
- [x] Len
- [x] Range
- [x] Has
- [x] Clear
- [x] Get
- [x] Set
- [x] Mutable
- [x] NewValue
- [x] IsValid

Ex for https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/reflect/protoreflect#Message `Has` method:
```go
func (foo *Foo) Has(f FieldDescriptor) bool {
  switch f.Number() {
    case 1:
      return foo.Bar != nil
    default:
      return false
  }
}
```

If we wanted to reuse the default protoreflect implementation, maybe this will work but it won't speed up other code:
```go
func (foo *Foo) Has(f FieldDescriptor) bool {
  switch f.Number() {
    case 1:
      return foo.Bar != nil
    default:
      return f.ProtoReflect().Has(f)
  }
}
```

Implementing all of the `protoreflect.Message` methods to be as fast as possible is the goal. Some benchmarks are here: https://github.com/cosmos/cosmos-sdk/discussions/9156#discussioncomment-1004213.

**Comment by fdymylja** [comment]
I could take care of implementing this.

Adding here more findings regarding my experimentations:

>I ran some benches to output some concrete numbers of using the protoreflect approach vs golang reflection vs two >autogenerated fast reflection paths:
>
>cpu: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
>
>protoreflect:
>Benchmark_ProtoReflect-12 12509864 86.64 ns/op
>
>golang reflection:
>Benchmark_GoReflection-12 14749225 70.45 ns/op
>
>reflection fast path with field descriptor:
>Benchmark_FastPath-12 70583667 16.33 ns/op
>
>reflection fast path with field name:
>Benchmark_GetFieldByName-12 282286454 4.331 ns/op

I was experimenting by creating an object which wraps the fast reflection API logic, in order not to pollute the object with many methods (especially in case we might extend this interface in the future): 

```go
// autogenerated by our impl
type messageTestFastReflection {
    x *TestFastReflection
}

func (x messageTestFastReflection) GetFieldByName(name protoreflect.Name) {
... logic
}

// autogenerated by protoc-gen-go
type TestFastReflection {
}


func (x *TestFastReflection) FastReflection() messageFastReflection {
   return messageTestFastReflection{x}
}
```

For reasons unknown to me, this approach, on top of making the object API less polluted, it's also faster:

```go
Benchmark_GetFieldByNameFastReflectionObject-12         317461324
 3.355 ns/op
```

**Comment by aaronc** [comment]
That would be great @fdymylja 👍 

@technicallyty can you push your latest code to a branch? Let's find a way to coordinate with PRs. 

I think it makes sense to just implement the whole `protoreflect.Message` with the fast path. Then every API can take advantage of the performance boost and we don't need to create another API.

**Comment by technicallyty** [comment]
updated my [branch](https://github.com/cosmos/cosmos-proto/tree/ty/pulsar-msg_interface) with my latest progress

**Comment by aaronc** [comment]
Looks like all the `protoreflect.Message` methods are generated here: https://github.com/cosmos/cosmos-proto/blob/ty/pulsar-msg_interface/generator/protoMessage.go. So this is where we would update the fast path codegen. Not sure if it makes sense to start with PRs against your branch. Maybe let's coordinate on discord?
