### ISSUE TITLE
Should message structs implement protoreflect.Message directly?

### ISSUE THREAD

**Issue by aaronc** [cosmos/cosmos-proto#7]
Currently we're generating custom `protoreflect.Message` methods on the message struct itself. But this may unnecessarily pollute the methods that all structs implement. What if a user wanted to implement a method named `Has` or `Range` for instance? They wouldn't be able to do it because it would conflict with the generated code.

An alternative would be a wrapper struct that implements `protoreflect.Message`, i.e.:

```go
type barReflect struct {
  *Bar
}

func (x *Bar) ProtoReflect() protoreflect.Message {
	return barReflect{x}
}
```

**Comment by fdymylja** [comment]
We should benchmark performance of doing this (just for the sake of it, especially if we plan to rely a lot on reflection), but I think it might be better to follow this path.

**Comment by fdymylja** [comment]
I think we need to implement messages with a separate structure for protoreflect, reason being that we're blocking the `Descriptor` function which is required for protov1 API compatibility.

**Comment by aaronc** [comment]
Could we use a type alias instead of a struct to reduce allocation?

**Comment by fdymylja** [comment]
> Could we use a type alias instead of a struct to reduce allocation?

Tomorrow I will try to do it following this approach, on paper it should work.

**Comment by fdymylja** [comment]
confirmed: I'm using a type alias and everything works as expected, to get protoreflect.Message implementation we just cast the `message` to the protoreflect.Message type implementer:

```go

type reflection_ProtoMessage ProtoMessage

type ProtoMessage struct {}

func (x *ProtoMessage) ProtoReflect() protoreflect.Message {
   return (*reflection_ProtoMessage)(x)
}   
```

**Comment by aaronc** [comment]
Seems like this is done in your PR @fdymylja so closing this
